# -*- coding: utf-8 -*-
"""airline_reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPmBG4T8FJ2eoLsRaC6wP4PzNsA2KMZR
"""

import pandas as pd
import nltk
from collections import defaultdict

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

def extract_important_words(text):
    words = nltk.word_tokenize(text)
    tagged_words = nltk.pos_tag(words)
    important_words = [word.lower().strip() for word, pos in tagged_words if pos in ['NNP', 'JJ']]
    return important_words

file_path = '/content/drive/MyDrive/Datasets Normalization/Airline Reviews/AirlineReviews.csv'
df = pd.read_csv(file_path)

user_ids = {name: idx for idx, name in enumerate(df['Name'].unique(), 1)}
df['userId'] = df['Name'].map(user_ids)

cols = df.columns.tolist()
cols.insert(cols.index('Name'), cols.pop(cols.index('userId')))
df = df[cols]

df['review_tags'] = df['ReviewHeader'].apply(lambda x: ', '.join(extract_important_words(str(x))) if isinstance(x, str) else '')

word_to_id = defaultdict(lambda: len(word_to_id) + 1)
df['tagId'] = df['review_tags'].apply(lambda x: ', '.join([str(word_to_id[word]) for word in x.split(', ')]))

cols = df.columns.tolist()
cols.insert(cols.index('ReviewHeader') + 1, cols.pop(cols.index('review_tags')))
cols.insert(cols.index('review_tags') + 1, cols.pop(cols.index('tagId')))
df = df[cols]

output_file_path = '/content/drive/MyDrive/Datasets Normalization/Airline Reviews/processed_AirlineReviews.csv'
df.dropna().to_csv(output_file_path, index=False)

print("Done!")